### ISSUE TITLE
Parser fails occasionally

### ISSUE THREAD

**Issue by amaanq** [vito/tree-sitter-bass#1]
From your bass repo:
```
examples/bass/bass/bass.bass                                                    1 ms    (ERROR [45, 34] - [45, 35])
examples/bass/demos/go-build-git.bass                                           0 ms    (MISSING symbol [9, 6] - [9, 6])
examples/bass/demos/multi-fail.bass                                             0 ms    (MISSING symbol [5, 6] - [5, 6])
examples/bass/pkg/runtimes/testdata/lib/thunk-path-lib.bass                     0 ms    (MISSING symbol [5, 17] - [5, 17])
examples/bass/pkg/runtimes/testdata/mount-run-dir.bass                          0 ms    (MISSING symbol [8, 48] - [8, 48])
examples/bass/pkg/runtimes/testdata/remount-workdir-subdir.bass                 0 ms    (MISSING symbol [12, 28] - [12, 28])
examples/bass/pkg/runtimes/testdata/remount-workdir.bass                        0 ms    (MISSING symbol [5, 17] - [5, 17])
examples/bass/std/git.bass                                                      0 ms    (MISSING symbol [23, 27] - [23, 27])
examples/bass/std/run.bass                                                      0 ms    (ERROR [59, 44] - [59, 46])     
```

I'll work on this a bit, but I'm not too familiar with bass. My plan was to tidy up the repo and then add it to nvim-treesitter.

**Comment by vito** [comment]
Interesting, thanks for the report!

It looks like all of these failures are related to path parsing, which I had the most difficulty implementing by far. :sweat_smile:

Some pointers:

* [paths](https://bass-lang.org/bassics.html#paths)
* [thunk paths](https://bass-lang.org/bassics.html#term-thunk%20path)

The tl;dr is that you can do things like this:

```clojure
(def my-path  ./)
(def sub-dir  my-path/subdir/) ; <- trailing slash
(def sub-file my-path/subfile) ; <- no trailing slash
```

This is a little tricky parser-wise because it means any symbol can turn into a path by affixing `/foo[/]` to it.

> I'll work on this a bit, but I'm not too familiar with bass. My plan was to tidy up the repo and then add it to nvim-treesitter.

That's exciting! Bass is a bit of a fringe language, so I'm not sure if it would be accepted upstream, but I'd certainly appreciate any time you find to help fix this parser up.

**Comment by amaanq** [comment]
nvim-treesitter has some of the wackiest languages added, don't worry bass would be totally accepted. I am kinda thinking to rewrite parts of this (I've written quite a few grammars) to alleviate this issue, but I'd like your nod of approval before spending some time on this.

So far I've fixed dots succeeding a slash, but not those in the middle of a path. I don't particularly like the regex constructs at the top, so I'd rework the symbol and path logic a bit which would fix everything but...be a rewrite :)

**Comment by vito** [comment]
@amaanq By all means, rewrite if you like! This was my first grammar and it's just based on the most similar starting point I could find.
